# company_urls.py

company_urls = {
    "Tata Consultancy Services (TCS)": "https://www.tcs.com/",
    "Infosys": "https://www.infosys.com/",
    "HCL Technologies": "https://www.hcltech.com/",
    "Wipro": "https://www.wipro.com/",
    "Tech Mahindra": "https://www.techmahindra.com/",
    "LTIMindtree": "https://www.ltimindtree.com/",
    "Mphasis": "https://www.mphasis.com/",
    "Persistent Systems": "https://www.persistent.com/",
    "Coforge": "https://www.coforge.com/",
    "Zensar Technologies": "https://www.zensar.com/",
    "Oracle Financial Services Software": "https://www.oracle.com/industries/financial-services/",
    "KPIT Technologies": "https://www.kpit.com/",
    "L&T Technology Services": "https://www.ltts.com/",
    "Tata Elxsi": "https://www.tataelxsi.com/",
    "Birlasoft": "https://www.birlasoft.com/",
    "Cyient": "https://www.cyient.com/",
    "Mastek": "https://www.mastek.com/",
    "eClerx Services": "https://www.eclerx.com/",
    "NIIT Technologies": "https://www.coforge.com/",  # NIIT Technologies rebranded to Coforge
    "Hexaware Technologies": "https://hexaware.com/",
    "Sasken Technologies": "https://www.sasken.com/",
    "Intellect Design Arena": "https://www.intellectdesign.com/",
    "Newgen Software Technologies": "https://newgensoft.com/",
    "Ramco Systems": "https://www.ramco.com/",
    "Sonata Software": "https://www.sonata-software.com/",
    "Aurionpro Solutions": "https://www.aurionpro.com/",
    "Tanla Platforms": "https://www.tanla.com/",
    "Happiest Minds Technologies": "https://www.happiestminds.com/",
    "Route Mobile": "https://www.routemobile.com/",
    "Affle (India)": "https://www.affle.com/",
    "Nazara Technologies": "https://nazaratechnologies.com/",
    "Subex": "https://www.subex.com/",
    "3i Infotech": "https://www.3i-infotech.com/",
    "Datamatics Global Services": "https://www.datamatics.com/",
    "Kellton Tech Solutions": "https://www.kellton.com/",
    "Saksoft": "https://www.saksoft.com/",
    "Nucleus Software Exports": "https://www.nucleussoftware.com/",
    "R Systems International": "https://www.rsystems.com/",
    "Take Solutions": "https://www.takesolutions.com/",
    "OnMobile Global": "https://www.onmobile.com/",
    "Allied Digital Services": "https://www.allieddigital.net/",
    "HOV Services": "https://www.hovsltd.com/",
    "Goldstone Technologies": "https://www.goldstonetech.com/",
    "FCS Software Solutions": "https://www.fcsltd.com/",
    "Megasoft": "https://www.megasoft.com/",
    "Zen Technologies": "https://www.zentechnologies.com/",
    "D-Link (India)": "https://in.dlink.com/",
    "Palred Technologies": "https://www.palred.com/",
    "Mindteck (India)": "https://www.mindteck.com/",
    "Expleo Solutions": "https://expleogroup.com/"
}
